/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Automatizacion;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author rafael
 */
public class ModeloDirecto extends javax.swing.JPanel {

    /**
     * Creates new form GraficaDatos
     */
    public ModeloDirecto()
    {
        initComponents();
        
        K="K";
        Tau="T";
        
    }
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        int xOffSet = 10;
        int yOffSet = 20;
        float fontSize = 18F;
        ancho = this.getWidth();
        alto = this.getHeight();
        

        g.setColor(Color.white);
        
        g.setFont(g.getFont().deriveFont(fontSize));
        
        if(!K.equals("K"))
            K = String.format("%.2f", Float.parseFloat(K));
        if(!Tau.equals("T"))
            Tau = String.format("%.2f", Float.parseFloat(Tau));
        g.drawString(K, ancho/2-g.getFontMetrics().stringWidth(K)/2, yOffSet);
        g.drawLine(xOffSet, alto/2, this.getWidth()-xOffSet, alto/2);
        g.drawString(Tau+"S + 1", ancho/2-g.getFontMetrics().stringWidth(Tau+"S + 1")/2, alto/2+yOffSet);
        

    }
    
    public void graficar()
    {
        graficar = true;
        repaint();
    }
    public void setK(String K)
    {
        this.K=K;
    }
    public void setTau(String Tau)
    {
        this.Tau=Tau;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private boolean graficar = false;
    private String K,Tau;
    int ancho;
    int alto;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
