/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Automatizacion;

import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author rafael
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        precisionBase = 0.5;
        precision = precisionBase*Math.pow(10,-1*jSlider1.getValue());
        jTextField1.setText(""+String.format("%.1e",precision));
        System.out.println("Precision:"+ precision);
        //dialogo = new VentanaDialogo(jDialog1);
        xi = "1.0";
        entonando = false;
        arrastrandoEntonacion = false;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jPanel13 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jTextField1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        graficaDatos = new Automatizacion.GraficaDatos();
        graficaModelos = new Automatizacion.GraficaModelos();
        jPanel7 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        graficaSalida1 = new Automatizacion.GraficaSalida();
        graficaSimulacion1 = new Automatizacion.GraficaSimulacion();
        jLabel36 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        modeloDirecto = new Automatizacion.ModeloDirecto();
        modeloFuerzaBruta = new Automatizacion.ModeloDirecto();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();

        jDialog1.setTitle("Por favor espere");
        jDialog1.setAlwaysOnTop(true);
        jDialog1.setMinimumSize(new java.awt.Dimension(500, 300));
        jDialog1.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        jDialog1.setResizable(false);
        jDialog1.setUndecorated(true);

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setMaximumSize(new java.awt.Dimension(500, 300));
        jPanel10.setMinimumSize(new java.awt.Dimension(500, 300));

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD, jLabel4.getFont().getSize()+2));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Por favor espere mientras se realizan los cálculos");
        jLabel4.setDoubleBuffered(true);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel4)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jFrame1.setTitle("Ajustes de Entonacion");
        jFrame1.setAlwaysOnTop(true);
        jFrame1.setMinimumSize(new java.awt.Dimension(573, 300));
        jFrame1.setResizable(false);

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));

        jLabel9.setFont(jLabel9.getFont().deriveFont(jLabel9.getFont().getStyle() | java.awt.Font.BOLD, jLabel9.getFont().getSize()+2));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("K:");

        jLabel10.setFont(jLabel10.getFont().deriveFont(jLabel10.getFont().getStyle() | java.awt.Font.BOLD, jLabel10.getFont().getSize()+2));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tau:");

        jLabel11.setFont(jLabel11.getFont().deriveFont(jLabel11.getFont().getStyle() | java.awt.Font.BOLD, jLabel11.getFont().getSize()+2));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Xi:");

        jLabel15.setFont(jLabel15.getFont().deriveFont(jLabel15.getFont().getStyle() | java.awt.Font.BOLD, jLabel15.getFont().getSize()+2));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tas:");

        jSlider2.setMinimum(1);
        jSlider2.setEnabled(false);
        jSlider2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSlider2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider2MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSlider2MouseClicked(evt);
            }
        });
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });

        jSlider3.setMinimum(1);
        jSlider3.setEnabled(false);
        jSlider3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSlider3MouseClicked(evt);
            }
        });
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("1.0");

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("1.0");

        jLabel13.setFont(jLabel13.getFont().deriveFont(jLabel13.getFont().getStyle() | java.awt.Font.BOLD, jLabel13.getFont().getSize()+2));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Kp:");

        jLabel14.setFont(jLabel14.getFont().deriveFont(jLabel14.getFont().getStyle() | java.awt.Font.BOLD, jLabel14.getFont().getSize()+2));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ki:");

        jLabel31.setFont(jLabel31.getFont().deriveFont(jLabel31.getFont().getStyle() | java.awt.Font.BOLD, jLabel31.getFont().getSize()+2));
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Automatizacion/x.png"))); // NOI18N
        jLabel31.setText("Encuentre valores para Xi y Tas");

        jLabel25.setFont(jLabel25.getFont().deriveFont(jLabel25.getFont().getStyle() | java.awt.Font.BOLD, jLabel25.getFont().getSize()+2));
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Parámetros de Entonación");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel25))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel11))
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel15)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(316, 316, 316)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addContainerGap())
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(7, 7, 7)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))
                        .addComponent(jLabel14))
                    .addContainerGap(120, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrame2.setTitle("Ajustes de Entonacion");
        jFrame2.setAlwaysOnTop(true);
        jFrame2.setMinimumSize(new java.awt.Dimension(500, 300));
        jFrame2.setResizable(false);

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setMaximumSize(new java.awt.Dimension(500, 300));
        jPanel13.setMinimumSize(new java.awt.Dimension(500, 300));
        jPanel13.setPreferredSize(new java.awt.Dimension(500, 300));

        jSlider1.setValue(5);
        jSlider1.setEnabled(false);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("1.0");

        jLabel22.setFont(jLabel22.getFont().deriveFont(jLabel22.getFont().getStyle() | java.awt.Font.BOLD, jLabel22.getFont().getSize()+2));
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Precisión para Búsqueda de Fuerza Bruta");

        jLabel23.setFont(jLabel23.getFont().deriveFont(jLabel23.getFont().getStyle() | java.awt.Font.BOLD, jLabel23.getFont().getSize()+2));
        jLabel23.setForeground(new java.awt.Color(255, 51, 51));
        jLabel23.setText("Incrementar demasiado la precisión podría");

        jLabel24.setFont(jLabel24.getFont().deriveFont(jLabel24.getFont().getStyle() | java.awt.Font.BOLD, jLabel24.getFont().getSize()+2));
        jLabel24.setForeground(new java.awt.Color(255, 51, 51));
        jLabel24.setText("colgar el ordenador. Usar con precaución.");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addGap(128, 128, 128)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addComponent(jLabel22))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Kurven");
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea2.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setForeground(new java.awt.Color(0, 153, 0));
        jTextArea2.setRows(5);
        jTextArea2.setText(" >> Bienvenido a Kurven...\n >> ");
        jTextArea2.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTextArea2);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Automatizacion/32 (2).png"))); // NOI18N
        jButton1.setToolTipText("Abrir nuevo archivo de entrada");
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Automatizacion/32 (1).png"))); // NOI18N
        jButton2.setToolTipText("Modelar curva reacción");
        jButton2.setEnabled(false);
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Automatizacion/32 (3).png"))); // NOI18N
        jButton3.setToolTipText("Modelar fuerza bruta");
        jButton3.setEnabled(false);
        jButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Automatizacion/32 (4).png"))); // NOI18N
        jButton4.setToolTipText("Entonar controlador");
        jButton4.setEnabled(false);
        jButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Automatizacion/32 (10).png"))); // NOI18N
        jButton5.setToolTipText("Fuzzy Auto-Tuning");
        jButton5.setEnabled(false);
        jButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Automatizacion/32 (5).png"))); // NOI18N
        jButton8.setToolTipText("Simular");
        jButton8.setEnabled(false);
        jButton8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Automatizacion/32 (6).png"))); // NOI18N
        jButton9.setToolTipText("Ajuste de parámetros de fuerza bruta");
        jButton9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Automatizacion/32 (7).png"))); // NOI18N
        jButton10.setToolTipText("Ajuste de parámetros de entonación");
        jButton10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Automatizacion/32 (8).png"))); // NOI18N
        jButton11.setToolTipText("Ayuda de Kurven");
        jButton11.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1)
            .addComponent(jButton2)
            .addComponent(jButton3)
            .addComponent(jButton4)
            .addComponent(jButton5)
            .addComponent(jButton8)
            .addComponent(jButton9)
            .addComponent(jButton10)
            .addComponent(jButton11)
        );

        jLayeredPane1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout graficaDatosLayout = new javax.swing.GroupLayout(graficaDatos);
        graficaDatos.setLayout(graficaDatosLayout);
        graficaDatosLayout.setHorizontalGroup(
            graficaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
        );
        graficaDatosLayout.setVerticalGroup(
            graficaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        graficaDatos.setBounds(0, 0, 1027, 500);
        jLayeredPane1.add(graficaDatos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setOpaque(false);

        jCheckBox1.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBox1.setForeground(java.awt.Color.cyan);
        jCheckBox1.setText("Modelo Datos");
        jCheckBox1.setEnabled(false);
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBox2.setForeground(java.awt.Color.magenta);
        jCheckBox2.setText("Modelo Directo");
        jCheckBox2.setEnabled(false);
        jCheckBox2.setOpaque(false);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBox3.setForeground(java.awt.Color.orange);
        jCheckBox3.setText("Modelo Fuerza Bruta");
        jCheckBox3.setEnabled(false);
        jCheckBox3.setOpaque(false);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setOpaque(false);

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getStyle() | java.awt.Font.BOLD, jLabel7.getFont().getSize()+2));
        jLabel7.setForeground(java.awt.Color.magenta);
        jLabel7.setText("ISE MD:");

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getStyle() | java.awt.Font.BOLD, jLabel8.getFont().getSize()+2));
        jLabel8.setForeground(java.awt.Color.orange);
        jLabel8.setText("ISE FB:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout graficaModelosLayout = new javax.swing.GroupLayout(graficaModelos);
        graficaModelos.setLayout(graficaModelosLayout);
        graficaModelosLayout.setHorizontalGroup(
            graficaModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graficaModelosLayout.createSequentialGroup()
                .addContainerGap(666, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        graficaModelosLayout.setVerticalGroup(
            graficaModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graficaModelosLayout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addGroup(graficaModelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        graficaModelos.setBounds(0, 0, 1030, 500);
        jLayeredPane1.add(graficaModelos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout graficaSalida1Layout = new javax.swing.GroupLayout(graficaSalida1);
        graficaSalida1.setLayout(graficaSalida1Layout);
        graficaSalida1Layout.setHorizontalGroup(
            graficaSalida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        graficaSalida1Layout.setVerticalGroup(
            graficaSalida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        graficaSalida1.setBounds(0, 0, 1030, 500);
        jLayeredPane1.add(graficaSalida1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel36.setFont(jLabel36.getFont().deriveFont(jLabel36.getFont().getStyle() | java.awt.Font.BOLD, jLabel36.getFont().getSize()+2));
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Simulación en Z con Sistema Discretizado");

        javax.swing.GroupLayout graficaSimulacion1Layout = new javax.swing.GroupLayout(graficaSimulacion1);
        graficaSimulacion1.setLayout(graficaSimulacion1Layout);
        graficaSimulacion1Layout.setHorizontalGroup(
            graficaSimulacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graficaSimulacion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
                .addContainerGap())
        );
        graficaSimulacion1Layout.setVerticalGroup(
            graficaSimulacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graficaSimulacion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addContainerGap(472, Short.MAX_VALUE))
        );

        graficaSimulacion1.setBounds(0, 0, 1027, 500);
        jLayeredPane1.add(graficaSimulacion1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout modeloDirectoLayout = new javax.swing.GroupLayout(modeloDirecto);
        modeloDirecto.setLayout(modeloDirectoLayout);
        modeloDirectoLayout.setHorizontalGroup(
            modeloDirectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        modeloDirectoLayout.setVerticalGroup(
            modeloDirectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout modeloFuerzaBrutaLayout = new javax.swing.GroupLayout(modeloFuerzaBruta);
        modeloFuerzaBruta.setLayout(modeloFuerzaBrutaLayout);
        modeloFuerzaBrutaLayout.setHorizontalGroup(
            modeloFuerzaBrutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        modeloFuerzaBrutaLayout.setVerticalGroup(
            modeloFuerzaBrutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>Funciones de <br> Transferencia</html>");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Curva Reacción");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Fuerza Bruta");
        jLabel3.setOpaque(true);

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(jLabel12.getFont().deriveFont(jLabel12.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Controlador");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel12.setOpaque(true);

        jLabel28.setBackground(new java.awt.Color(0, 0, 0));
        jLabel28.setFont(jLabel28.getFont().deriveFont(jLabel28.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Kp:");
        jLabel28.setOpaque(true);

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(jLabel29.getFont().deriveFont(jLabel29.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Ki :");
        jLabel29.setOpaque(true);

        jLabel37.setBackground(new java.awt.Color(51, 51, 51));
        jLabel37.setFont(jLabel37.getFont().deriveFont(jLabel37.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Simulación");
        jLabel37.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel37.setOpaque(true);

        jLabel34.setFont(jLabel34.getFont().deriveFont(jLabel34.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Ref:");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0.0");
        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel38.setBackground(new java.awt.Color(51, 51, 51));
        jLabel38.setFont(jLabel38.getFont().deriveFont(jLabel38.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText(" Controlador 1");
        jLabel38.setOpaque(true);

        jLabel32.setFont(jLabel32.getFont().deriveFont(jLabel32.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Salida:");

        jLabel39.setFont(jLabel39.getFont().deriveFont(jLabel39.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Apagado");

        jButton6.setText("Detener");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel40.setBackground(new java.awt.Color(51, 51, 51));
        jLabel40.setFont(jLabel40.getFont().deriveFont(jLabel40.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText(" Controlador 2");
        jLabel40.setOpaque(true);

        jLabel33.setFont(jLabel33.getFont().deriveFont(jLabel33.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Salida:");

        jLabel41.setFont(jLabel41.getFont().deriveFont(jLabel41.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Apagado");

        jButton7.setText("Detener");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel42.setBackground(new java.awt.Color(51, 51, 51));
        jLabel42.setFont(jLabel42.getFont().deriveFont(jLabel42.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Planta");
        jLabel42.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel42.setOpaque(true);

        jLabel35.setFont(jLabel35.getFont().deriveFont(jLabel35.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Salida:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modeloFuerzaBruta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(modeloDirecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4)
                .addContainerGap())
            .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(37, 37, 37))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton6)
                .addContainerGap())
            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modeloDirecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modeloFuerzaBruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Modelo");

        jMenuItem3.setText("Modelar Curva Reaccion");
        jMenuItem3.setEnabled(false);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Modelar Fuerza Bruta");
        jMenuItem4.setEnabled(false);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Controlador");

        jMenuItem6.setText("Entonar");
        jMenuItem6.setEnabled(false);
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Fuzzy Auto-Tuning");
        jMenuItem7.setEnabled(false);
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Simulación");

        jMenuItem8.setText("Simular");
        jMenuItem8.setEnabled(false);
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Configuración");

        jMenuItem12.setText("Ajustar Parámetros de Fuerza Bruta");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenuItem5.setText("Ajustar Parámetros de Entonación");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Ayuda");

        jMenuItem9.setText("Ayuda");
        jMenu5.add(jMenuItem9);

        jMenuItem10.setText("Teoria");
        jMenu5.add(jMenuItem10);
        jMenu5.add(jSeparator1);

        jMenuItem11.setText("Acerca de Kurven...");
        jMenu5.add(jMenuItem11);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(this.jCheckBox1.isSelected())
        {
            graficaModelos.graficarD();
        }
        else
        {
            graficaModelos.degraficarD();
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if(this.jCheckBox2.isSelected())
        {
            graficaModelos.graficarMD();
        }
        else
        {
            graficaModelos.degraficarMD();
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(this.jCheckBox3.isSelected())
        {
            graficaModelos.graficarFB();
        }
        else
        {
            graficaModelos.degraficarFB();
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        // TODO add your handling code here:  
    }//GEN-LAST:event_jSlider2StateChanged

    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3StateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jSlider3StateChanged

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
        graficaSimulacion1.setRef(jTextField4.getText());
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jButton6.setEnabled(false);
        graficaSimulacion1.matarU1();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jButton7.setEnabled(false);
        graficaSimulacion1.matarU2();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        nuevo();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        nuevo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        encontrarModeloDirecto();
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        graficarModeloFuerzaBruta();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        entonar();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider1StateChanged

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        jFrame2.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        
        simular();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        encontrarModeloDirecto();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        graficarModeloFuerzaBruta();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        entonar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        autoFuzzy();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:]
        simular();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jSlider2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider2MouseClicked
        // TODO add your handling code here:
        nuevosParametrosEntonacion();
    }//GEN-LAST:event_jSlider2MouseClicked

    private void jSlider3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider3MouseClicked
        // TODO add your handling code here:
        nuevosParametrosEntonacion();
    }//GEN-LAST:event_jSlider3MouseClicked

    private void jSlider2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider2MousePressed
        // TODO add your handling code here:
        arrastrandoEntonacion = true;
    }//GEN-LAST:event_jSlider2MousePressed

    private void jSlider2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider2MouseReleased
        // TODO add your handling code here:
        if(arrastrandoEntonacion)
            nuevosParametrosEntonacion();
        else
            arrastrandoEntonacion = false;
    }//GEN-LAST:event_jSlider2MouseReleased

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        autoFuzzy();
    }//GEN-LAST:event_jMenuItem7ActionPerformed
    
    public void autoFuzzy()
    {
        jLayeredPane1.moveToFront(graficaSalida1);
        
        jButton8.setEnabled(true);
        jMenuItem8.setEnabled(true);
        JOptionPane.showMessageDialog(this, "Kurven procedera a calcular la nueva sintonización mediante lógica difusa, por favor espere hasta ver la gráfica obtenida");
        
        try
        {
            Runtime rt = Runtime.getRuntime();

            Process pr = rt.exec("./fuzzytuning datos.txt "+mk+" "+mt);
            System.out.println("./fuzzytuning datos.txt "+mk+" "+mt);
 
            BufferedReader input = new BufferedReader(new InputStreamReader(pr.getInputStream()));
 
            String line=input.readLine();
            line = line.substring(1,line.length());
            imprimirConsola("Fuzzyficando... 1/4");
            System.out.println(line);
            
            line=input.readLine();
            line = line.substring(1,line.length());
            imprimirConsola("Infiriendo... 2/4");
            System.out.println(line);
            
            line=input.readLine();
            line = line.substring(1,line.length());
            imprimirConsola("Defuzzyficando... 3/4");
            System.out.println(line);
            
            
            String xy[] = line.split(",");
            kp = xy[0];
            ki = xy[1];
            
            String aux = "Ki: "+String.format("%.2e",Float.parseFloat(ki));
            jLabel13.setText(aux);
            jLabel28.setText(aux);
            aux = "Kp: "+String.format("%.2e",Float.parseFloat(kp));
            jLabel14.setText(aux);
            jLabel29.setText(aux);
            
            imprimirConsola("Probando nuevos valores con la planta ... 4/4");
            
            Process pr2 = rt.exec("./aeulc 0.1 0.01 30 "+mk+" "+mt+" "+kp+" "+ki+" respuesta_escalon.txt");
            
            input = new BufferedReader(new InputStreamReader(pr2.getInputStream()));
            
            puntos.clear();
            
            imprimirConsola("Graficando nueva sintonización...");
            
            while((line=input.readLine()) != null)
            {
                xy = line.split(",");
                Punto p = new Punto(Float.parseFloat(xy[0]),Float.parseFloat(xy[1]));
                puntos.add(p);
                
                graficaSalida1.setPuntosSalida(puntos);
                graficaSalida1.graficarSalida();
            }
            
            puntos.clear();

            jLabel31.setIcon(new ImageIcon(getClass().getResource("/Automatizacion/check.png")));
            jLabel31.setText("Estos valores satisfacen el sistema de control");
            
        }
        catch(Exception e)
        {
            jLabel31.setIcon(new ImageIcon(getClass().getResource("/Automatizacion/x.png")));
            jLabel31.setText("Valores no óptimos. Intente nuevos valores!");
            
            System.err.println(e.toString());
        }
    }
    
    public void nuevosParametrosEntonacion()
    {
        if(entonando)
            return;
        else
            entonando = true;
        
            jSlider2.setEnabled(false);
            jSlider3.setEnabled(false);
            jLabel31.setText("Por favor espere...");
            jLabel31.setIcon(new ImageIcon(getClass().getResource("/Automatizacion/wait.png")));
        
        tas = Integer.toString(jSlider3.getValue());
        jTextField3.setText(tas);
        
        xi = Float.toString((float)jSlider2.getValue()/50.0F);
        jTextField2.setText(xi);
        
        try
        {
            Runtime rt = Runtime.getRuntime();

            Process pr = rt.exec("./calcular_ganancias "+mk+" "+mt+" "+xi+" "+tas);
 
            BufferedReader input = new BufferedReader(new InputStreamReader(pr.getInputStream()));
 
            String line=input.readLine();
            System.out.println(line);
            String xy[] = line.split(",");
            ki = xy[0];
            kp = xy[1];
            
            String aux = "Ki: "+String.format("%.2e",Float.parseFloat(ki));
            jLabel13.setText(aux);
            jLabel28.setText(aux);
            aux = "Kp: "+String.format("%.2e",Float.parseFloat(kp));
            jLabel14.setText(aux);
            jLabel29.setText(aux);
            
            Process pr2 = rt.exec("./aeulc 0.1 0.01 30 "+mk+" "+mt+" "+kp+" "+ki+" respuesta_escalon.txt");
            
            input = new BufferedReader(new InputStreamReader(pr2.getInputStream()));
            
            puntos.clear();
            
            while((line=input.readLine()) != null)
            {
                xy = line.split(",");
                Punto p = new Punto(Float.parseFloat(xy[0]),Float.parseFloat(xy[1]));
                puntos.add(p);
                
                graficaSalida1.setPuntosSalida(puntos);
                graficaSalida1.graficarSalida();
            }
            
            puntos.clear();
            
            
            
            
            
            jLabel31.setIcon(new ImageIcon(getClass().getResource("/Automatizacion/check.png")));
            jLabel31.setText("Estos valores satisfacen el sistema de control");
            
        }
        catch(Exception e)
        {
            jLabel31.setIcon(new ImageIcon(getClass().getResource("/Automatizacion/x.png")));
            jLabel31.setText("Valores no óptimos. Intente nuevos valores!");
            
            System.err.println(e.toString());
        }
        entonando = false;
        jSlider3.setEnabled(true);
            jSlider2.setEnabled(true);
    }
    
    public void simular()
    {
        jLayeredPane1.moveToFront(graficaSimulacion1);
        
        new Thread(graficaSimulacion1).start();
        graficaSimulacion1.graficarSalida(mk,mt,ts,kp,ki,jLabel32,jLabel33,jLabel35,this);
        

            jTextField4.setEnabled(true);
            jButton6.setEnabled(true);
            jButton7.setEnabled(true);
    }
    
    public void entonar()
    {
        jFrame1.setVisible(true);
        jLayeredPane1.moveToFront(graficaSalida1);
        
        jButton8.setEnabled(true);
        jMenuItem8.setEnabled(true);
    }
    
    public void salir()
    {
        System.out.println("Cerrando");
        if(graficaSimulacion1.isEnabled())
            graficaSimulacion1.detener();
        try {
            Thread.sleep(5000);
        } catch (InterruptedException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Runtime rt = Runtime.getRuntime();
            
        Process pr;
        try
        {
            pr = rt.exec("pgrep planta");
            BufferedReader input = new BufferedReader(new InputStreamReader(pr.getInputStream()));
            String line=input.readLine();
            
            while(line!=null)
            {
                pr = rt.exec("kill "+line);
                System.out.println("kill "+line);

                pr = rt.exec("pgrep planta");      
                line=input.readLine();
            }
            
            pr = rt.exec("pgrep operador");
            input = new BufferedReader(new InputStreamReader(pr.getInputStream()));
            line=input.readLine();
            
            while(line!=null)
            {
                pr = rt.exec("kill "+line);
                System.out.println("kill "+line);

                pr = rt.exec("pgrep operador");      
                line=input.readLine();
            }
            
            pr = rt.exec("pgrep controlador_a");
            input = new BufferedReader(new InputStreamReader(pr.getInputStream()));
            line=input.readLine();
            
            while(line!=null)
            {
                pr = rt.exec("kill "+line);
                System.out.println("kill "+line);

                pr = rt.exec("pgrep controlador_a");      
                line=input.readLine();
            }
            
            pr = rt.exec("pgrep controlador_b");
            input = new BufferedReader(new InputStreamReader(pr.getInputStream()));
            line=input.readLine();
            
            while(line!=null)
            {
                pr = rt.exec("kill "+line);
                System.out.println("kill "+line);

                pr = rt.exec("pgrep controlador_b");      
                line=input.readLine();
            }
        }
        catch (IOException ex)
        {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            Thread.sleep(5000);
        } catch (InterruptedException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }
    
    public void nuevo()
    {
        final JFileChooser fc = new JFileChooser();
        
                
        //In response to a button click:
        int returnVal = fc.showOpenDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION)
        {
            file = fc.getSelectedFile();

            imprimirConsola("Abriendo archivo: " + file.getAbsolutePath());
            
            try
            {
                FileWriter fw = new FileWriter("datos.txt");
                PrintWriter pw = new PrintWriter(fw);
                
                BufferedReader in = new BufferedReader(new FileReader(file));
                String str;
                
                puntos.clear();

                while ((str = in.readLine()) != null)
                {
                    //System.out.println(str);
                    String xy[] = str.split(",");
                    Punto p = new Punto(Float.parseFloat(xy[0]),Float.parseFloat(xy[1]));
                    puntos.add(p);
                    
                    pw.println(Float.parseFloat(xy[0])+","+Float.parseFloat(xy[1]));
                }
                
                pw.close();
                fw.close();
                
                n = Float.toString(puntos.get(puntos.size()-1).getX());
                //System.out.println(n);
                
                /*
                if(puntos.size() > 1)
                {
                    ts = Float.toString(puntos.get(1).getX()-puntos.get(0).getX());
                }
                */
                //System.out.println(puntos.size());
                ts = "1.0";
                pw.close();
                in.close();
                //jButton2.setEnabled(true);
                //jButton3.setEnabled(true);
                
                Runtime rt = Runtime.getRuntime();
            
            
            
                Process pr = rt.exec("./comprobar_orden_uno");
 
                BufferedReader input = new BufferedReader(new InputStreamReader(pr.getInputStream()));
 
                String line=input.readLine();
                
                if(line.equalsIgnoreCase("S"))
                {
                    imprimirConsola("Los datos muestreados, representan un comportamiento de un sistema de Primer Orden");
                    JOptionPane.showMessageDialog(this, "Los datos muestreados, representan un comportamiento de un sistema de Primer Orden");
                }
                if(line.equalsIgnoreCase("N"))
                {
                    imprimirConsola("Los datos muestreados, representan un comportamiento de un sistema de Orden Superior. Este programa no es válido para este sistema.");
                    JOptionPane.showMessageDialog(this, "Los datos muestreados, representan un comportamiento de un sistema de Orden Superior. Este programa no es válido para este sistema.");
                }
                
                graficarNuevo();
                
                jMenuItem3.setEnabled(true);
                jButton2.setEnabled(true);
                
            }
            catch (Exception ex) { System.err.println(ex.toString()); }
        }
        else
        {
            System.out.println("Open command cancelled by user.");
        }
    }
    
    public void graficarNuevo()
    {
        graficaDatos.setPuntos(puntos);
        graficaDatos.graficar();
        
        graficaModelos.setPuntosD(puntos);
        graficaModelos.graficarD();
        
        this.jCheckBox1.setEnabled(true);
        this.jCheckBox1.setSelected(true);
    }
    
    public void encontrarModeloDirecto()
    {
        jLayeredPane1.moveToFront(graficaModelos);
        try
        {
            imprimirConsola("Buscando modelo directo... 1/3");
            
            Runtime rt = Runtime.getRuntime();
            //Process pr = rt.exec("cmd /c dir");
            
            
            Process pr = rt.exec("./ajuste_directo "+file.getAbsolutePath()+" resultado_modelo_directo.txt");
            //Process pr = rt.exec("./ada/a.out "+file.getAbsolutePath());
            
            imprimirConsola("Calculando modelo directo... 2/3");
 
            BufferedReader input = new BufferedReader(new InputStreamReader(pr.getInputStream()));
 
            String line=input.readLine();
            String xyz[] = line.split(",");
            
            kmd=Float.toString(Float.parseFloat(xyz[0]));
            tmd = Float.toString(Float.parseFloat(xyz[1]));
            isemd = Float.toString(Float.parseFloat(xyz[2]));
            
            jLabel7.setText("ISE MD: "+isemd);
            
            imprimirConsola("Graficando modelo directo... 3/3");
            
            modeloDirecto.setK(kmd);
            modeloDirecto.setTau(tmd);
            
            mise=isemd;
            mk = kmd;
            mt = tmd;
            jLabel9.setText("K: "+mk);
            jLabel10.setText("Tau: "+mt);
            //jLabel30.setText("Modelo: Directo");
            //jButton5.setEnabled(true);
            
            modeloDirecto.repaint();
            
            puntos.clear();
            
            while((line=input.readLine()) != null)
            {
                String xy[] = line.split(",");
                Punto p = new Punto(Float.parseFloat(xy[0]),Float.parseFloat(xy[1]));
                puntos.add(p);
                
            }
            
            
            
            graficaModelos.setPuntosMD(puntos);
            graficaModelos.graficarMD();
            
            puntos.clear();
            
            this.jCheckBox2.setEnabled(true);
            this.jCheckBox2.setSelected(true);
 
            jButton3.setEnabled(true);
            jMenuItem4.setEnabled(true);
        } 
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
    }
    
    public void graficarModeloFuerzaBruta()
    {
        try
        {
            //jFrame1.setVisible(true);
            //this.setEnabled(false);
            //jDialog1.setVisible(true);
            
            jLayeredPane1.moveToFront(graficaModelos);
            
            imprimirConsola("Buscando modelo fuerza bruta... 1/3");
            
            Runtime rt = Runtime.getRuntime();
            
            Process pr2 = rt.exec("./fbp1s 50000 "+kmd+" "+tmd+ " resultado_modelo_fb.txt");
            
            //System.out.println("./fbp1c localhost 50000 "+kmd+" "+tmd+" "+precision);
       
            Process pr = rt.exec("./fbp1c localhost 50000 "+kmd+" "+tmd+" "+precision+" resultado_modelo_fb.txt");
            
            
            BufferedReader input = new BufferedReader(new InputStreamReader(pr.getInputStream()));
            
 
            //Thread.sleep(20000);
            String line=input.readLine();
            String xyz[] = line.split(",");
            
            tfb=Float.toString(Float.parseFloat(xyz[0]));
            kfb = kmd;
            isefb = Float.toString(Float.parseFloat(xyz[1]));
            
            jLabel8.setText("ISE FB: "+isefb);
            
            modeloFuerzaBruta.setK(kmd);
            modeloFuerzaBruta.setTau(tfb);
            
            if(Float.parseFloat(isefb) < Float.parseFloat(isemd) )
            {
                mise=isefb;
                mk = kfb;
                mt = tfb;
                //jLabel30.setText("Modelo: Fuerza Bruta");
            }
            
            jLabel9.setText("K: "+mk);
            jLabel10.setText("Tau: "+mt);
            
            modeloFuerzaBruta.repaint();
            
            puntos.clear();
            
            imprimirConsola("Calculando modelo fuerza bruta... 2/3");
            
            while((line=input.readLine()) != null)
            {
                //System.out.println(line);
                String xy[] = line.split(",");
                Punto p = new Punto(Float.parseFloat(xy[0]),Float.parseFloat(xy[1]));
                puntos.add(p);
                
            }
            
            imprimirConsola("Graficando modelo fuerza bruta... 3/3");
            
            graficaModelos.setPuntosFB(puntos);
            graficaModelos.graficarFB();
            
            puntos.clear();
            
            this.jCheckBox3.setEnabled(true);
            this.jCheckBox3.setSelected(true);
            this.jSlider3.setMaximum((int)Float.parseFloat(n));
            this.jSlider3.setMinimum(1);
            jSlider3.setValue(6);
            jSlider3.setEnabled(true);
            jSlider2.setEnabled(true);
            
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            jMenuItem6.setEnabled(true);
            jMenuItem7.setEnabled(true);
            
            //int exitVal = pr.waitFor();
            //System.out.println("Exited with error code "+exitVal);
        } 
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
        
    }
    
    public void imprimirConsola(String salida)
    {
        jTextArea2.setText(jTextArea2.getText()+salida+"\n >> ");
    }
    

    
    private ArrayList<Punto> puntos = new ArrayList<Punto>();
    private File file=null;
    private String kmd="",tmd="",isemd="";
    private String kfb="",tfb="",isefb="";
    private String mk="", mt="",mise="";
    private String xi = "";
    private String ts="";
    private String ki="",kp="";
    private String n;
    private String tas;
    private double precision;
    private double precisionBase;
    private boolean entonando;
    private boolean arrastrandoEntonacion;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Automatizacion.GraficaDatos graficaDatos;
    private Automatizacion.GraficaModelos graficaModelos;
    private Automatizacion.GraficaSalida graficaSalida1;
    private Automatizacion.GraficaSimulacion graficaSimulacion1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private Automatizacion.ModeloDirecto modeloDirecto;
    private Automatizacion.ModeloDirecto modeloFuerzaBruta;
    // End of variables declaration//GEN-END:variables
}

